### PR TITLE
landing page ui update

### PR DESCRIPTION
**Pull request by Abhay-2811**

### CODE REVIEW

**Comment by nlok5923** [comment]
image

I think you misunderstood the task

the landing page should the home page should look like this itself

image

You can refer to this https://docs.fhenix.zone/

**Comment by Abhay-2811** [comment]
Actually it looks better in dark mode

**Comment by nlok5923** [comment]
Also, please use the brand font here and make sure all the text follows the same family

**Comment by nlok5923** [comment]
Merged it for now!

**Pull request merged**
